<!DOCTYPE html> 
<html> 
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="author" content="Archambault Laurent">
<meta name="keywords" content="Alfresco mini-tools Users and Files">
<meta name="description" content="Alfresco Mini Tools Users and Files">
<meta name="robots" content="all" >
<meta http-equiv="imagetoolbar" content="no" >
<meta name="geo.placename" content="Romorantin, Loir et Cher (41), France" >
<meta http-equiv="X-UA-Compatible" content="IE=9">
<style>@import url("css/default.css") screen, projection, tv;</style>
<body>
